session_id: 2022-06-22_ST18-01
block_id: block-order-10
objects_to_track:
- sticker_yellow
- sticker_blue
- sticker_green
source_video: 1_primary/kinect/2022-06-22_ST18-01/block-order-10/2022-06-22_ST18-01_semicontrolled_block-order10_kinect.mkv
stimulus_metadata: 1_primary/logs/2_stimuli_by_blocks/2022-06-22_ST18-01/2022-06-22_ST18-01_semicontrolled_block-order10_stimuli.csv
hand_models_dir: handmesh_models
video_primary_output_dir: 1_primary/kinect/2022-06-22_ST18-01/block-order-10
video_processed_output_dir: 2_processed/kinect/2022-06-22_ST18-01/block-order-10
session_primary_output_dir: 1_primary/kinect/2022-06-22_ST18-01
session_processed_output_dir: 2_processed/kinect/2022-06-22_ST18-01
nerve_primary_dir: 1_primary/nerve/2022-06-22_ST18-01
nerve_processed_dir: 2_processed/nerve/3_cond-velocity-adj/2022-06-22_ST18-01
session_merged_output_dir: 3_merged/2022-06-22_ST18-01
